apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodejs
  labels:
    app: mynodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thiernosmynodejs
  template:
    metadata:
      labels:
        app: mynodejs
    spec:
      containers:
        - name: thiernos
          image: 223273133675.dkr.ecr.eu-west-3.amazonaws.com/thiernos:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
