apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poukalnodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: poukal
          image: 223273133675.dkr.ecr.eu-west-3.amazonaws.com/poukal:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
